{
    "name": "Print Estimation",
    "summary": "Estimating, costing and production masters for offset/digital print, books and packaging",
    "version": "19.0.1.0.0",
    "category": "Manufacturing/Print",
    "author": "Khurram",
    "license": "LGPL-3",
    "depends": ["base", "mail", "product"],
    "data": [
        "security/print_security.xml",
        "security/ir.model.access.csv",
        "data/product_group_data.xml",
        "data/format_data.xml",
        "data/imposition_data.xml",
        "views/product_group_views.xml",
        "views/material_views.xml",
        "views/labour_views.xml",
        "views/workcenter_views.xml",
        "views/cost_group_views.xml",
        "views/factor_views.xml",
        "views/imposition_views.xml",
        "views/format_views.xml",
        "views/menus.xml",
    ],
    "application": True,
    "installable": True,
}
