{
    "name": "Print Production Core",
    "summary": "Estimating, costing and production masters for offset/digital print, books and packaging",
    "version": "19.0.1.1.1",
    "category": "Manufacturing/Print",
    "author": "Khurram",
    "license": "LGPL-3",
    "depends": ["base", "mail", "product"],
    "data": [
        "security/print_security.xml",
        "security/ir.model.access.csv",
        "data/product_group_data.xml",
        "data/format_data.xml",
        "data/imposition_data.xml",
        "data/sequence_data.xml",
        "data/page_type_data.xml",
        "views/product_group_views.xml",
        "views/material_views.xml",
        "views/labour_views.xml",
        "views/workcenter_views.xml",
        "views/cost_group_views.xml",
        "views/factor_views.xml",
        "views/imposition_views.xml",
        "views/format_views.xml",
        "views/page_type_views.xml",
        "views/estimate_views.xml",
        "views/print_line_views.xml",
        "views/res_config_settings_views.xml",
        "views/menus.xml",
    ],
    "application": True,
    "installable": True,
}
