# -*- coding: utf-8 -*-
from odoo import _, api, fields, models
from odoo.exceptions import UserError


class AwDesign(models.Model):
    """One configured window/door position — the direct port of the JS
    prototype's QUOTE.designs[] entry. The one deliberate departure from
    the prototype: this ties to a real sale.order.line instead of living
    in a standalone quote object, so Odoo's own pricing/discount/tax/PDF/
    portal machinery applies rather than being rebuilt in parallel.

    Row/leaf geometry lives in aw.design.row / aw.design.leaf (children).
    Profile cut list lives in aw.design.bom.line, GENERATED by the
    explosion engine — not part of this module yet, see action_explode().
    """
    _name = 'aw.design'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _description = 'Fenestration Design'
    _order = 'id'

    name = fields.Char(
        required=True, tracking=True,
        help="Position reference, e.g. 'D1' — matches the prototype's "
             "design.ref, shown on the cumulative cut-list table.")
    location = fields.Char(tracking=True, help="e.g. 'Drawing room', "
        "'Bathroom' — matches the prototype's design.loc.")
    qty = fields.Integer(default=1, required=True, tracking=True)
    active = fields.Boolean(default=True)

    # length_uom is NOT related to any stored field on res.company -- it's
    # a plain non-stored compute reading ir.config_parameter directly (see
    # aw_fenestration_core's res_config_settings.py for why: a required
    # stored field on a core model that's prefetched on every request is
    # exactly the risk class that took the whole site down once already).
    length_uom = fields.Selection([
        ('ftin', 'Feet + Inches'),
        ('in', 'Inches'),
        ('mm', 'Millimetres'),
    ], compute='_compute_length_uom', string='Length Unit')

    # -- geometry, overall opening --------------------------------------
    # mm is the stored source of truth; ft/in and inch_total are
    # compute+inverse display/entry pairs that read from and write back
    # to it, so editing in ANY unit keeps all three in sync and the view
    # can show only the pair matching length_uom.
    #
    # Deliberately NOT required=True. Two separate paths create a design
    # before any dimension is known: Add Position (which creates the
    # design, then opens its form to be filled in), and a new design form
    # where the user types into the ft/in pair -- those are non-stored
    # inverse fields, and the NOT NULL constraint fires at INSERT, before
    # the inverse that would populate *_mm ever runs. Both hit
    # "Missing required value for the field 'Width (mm)'". Zero is a
    # legitimate not-yet-filled-in state here; see
    # _check_dimensions_set(), which enforces real dimensions at the two
    # points where they actually have to exist.
    width_mm = fields.Float(string='Width (mm)', default=0.0, tracking=True)
    width_ft = fields.Integer(string='Width (ft)',
        compute='_compute_width_ftin', inverse='_inverse_width_ftin')
    width_in = fields.Float(string='Width (in)',
        compute='_compute_width_ftin', inverse='_inverse_width_ftin',
        help="Decimals allowed, e.g. 6.5.")
    width_inch_total = fields.Float(string='Width (in)',
        compute='_compute_width_inch_total', inverse='_inverse_width_inch_total')

    height_mm = fields.Float(string='Height (mm)', default=0.0, tracking=True)
    height_ft = fields.Integer(string='Height (ft)',
        compute='_compute_height_ftin', inverse='_inverse_height_ftin')
    height_in = fields.Float(string='Height (in)',
        compute='_compute_height_ftin', inverse='_inverse_height_ftin',
        help="Decimals allowed, e.g. 6.5.")
    height_inch_total = fields.Float(string='Height (in)',
        compute='_compute_height_inch_total', inverse='_inverse_height_inch_total')

    # -- master-data links -----------------------------------------------
    # Confirmed against models/window_template.py: window_type_id is still
    # the exact field name on aw.window.template (and aw.profile.section/
    # aw.hardware.set), unchanged across the Kind/Type/Series restructure —
    # only its comodel moved to aw.window.series. Domain below is correct.
    window_series_id = fields.Many2one(
        'aw.window.series', required=True, tracking=True, ondelete='restrict')
    template_id = fields.Many2one(
        'aw.window.template', tracking=True, ondelete='set null',
        domain="[('window_type_id', '=', window_series_id)]",
        help="Optional starting default — populates Profile Section / "
             "Hardware Set / Glass Spec choices below when picked. Not "
             "required: a design can be built without one.")
    glass_spec_id = fields.Many2one(
        'aw.glass.spec', tracking=True, ondelete='restrict')

    # -- finish / thickness -----------------------------------------------
    # These are product.attribute.value records (the Finish/Thickness
    # attributes created for the profile product import), not a hardcoded
    # Selection — so this module never has its own copy of "what finishes
    # exist" to keep in sync with the product catalogue. Confirmed the
    # attribute names against the live import: "Finish" (xmlid
    # aw_attribute_finish) and "Thickness" (xmlid aw_attribute_thickness)
    # in aw_fenestration_core/data/chawla_attributes_data.xml. Domains by
    # xmlid rather than by name string, matching the pattern already used
    # for categ_id in aw_fenestration_core's profile_section.py/
    # hardware_set.py/glass_spec.py -- a renamed attribute wouldn't
    # silently break this the way name-matching would.
    finish_id = fields.Many2one(
        'product.attribute.value', tracking=True,
        domain=lambda self: [(
            'attribute_id', '=',
            self.env.ref('aw_fenestration_core.aw_attribute_finish').id,
        )])
    thickness_id = fields.Many2one(
        'product.attribute.value', tracking=True,
        domain=lambda self: [(
            'attribute_id', '=',
            self.env.ref('aw_fenestration_core.aw_attribute_thickness').id,
        )])

    # -- pricing override, matches prototype's d.manual -------------------
    manual_rate = fields.Float(
        string='Manual Rate (per sqft)',
        help="If set, overrides the calculated rate — matches the "
             "prototype's manual-override mechanism. Leave blank to use "
             "calculated pricing once the cost cascade exists.")

    # -- Sale integration ---------------------------------------------------
    sale_order_line_id = fields.Many2one(
        'sale.order.line', ondelete='cascade', index=True,
        help="The line this design prices onto. May be blank while a "
             "design is still being configured pre-quote.")
    sale_order_id = fields.Many2one(
        related='sale_order_line_id.order_id', store=True, readonly=True)

    # -- children -----------------------------------------------------------
    row_ids = fields.One2many('aw.design.row', 'design_id', string='Rows')
    bom_line_ids = fields.One2many(
        'aw.design.bom.line', 'design_id', string='Bill of Materials')

    row_count = fields.Integer(compute='_compute_counts')
    leaf_count = fields.Integer(compute='_compute_counts')
    size_display = fields.Char(compute='_compute_size_display', string='Size')
    area_sqm = fields.Float(compute='_compute_area', store=True, string='Area (m²)')
    area_sqft = fields.Float(compute='_compute_area', store=True, string='Area (sqft)')

    @api.depends('row_ids.leaf_ids')
    def _compute_counts(self):
        for rec in self:
            rec.row_count = len(rec.row_ids)
            rec.leaf_count = sum(len(r.leaf_ids) for r in rec.row_ids)

    @api.depends()
    def _compute_length_uom(self):
        value = self.env['ir.config_parameter'].sudo().get_param(
            'aw_fenestration.length_uom', 'ftin')
        for rec in self:
            rec.length_uom = value

    @api.depends('width_mm')
    def _compute_width_ftin(self):
        for rec in self:
            total_in = rec.width_mm / 25.4
            ft = int(total_in // 12)
            rec.width_ft = ft
            rec.width_in = total_in - ft * 12

    def _inverse_width_ftin(self):
        for rec in self:
            rec.width_mm = rec.width_ft * 304.8 + rec.width_in * 25.4

    @api.depends('width_mm')
    def _compute_width_inch_total(self):
        for rec in self:
            rec.width_inch_total = rec.width_mm / 25.4

    def _inverse_width_inch_total(self):
        for rec in self:
            rec.width_mm = rec.width_inch_total * 25.4

    @api.depends('height_mm')
    def _compute_height_ftin(self):
        for rec in self:
            total_in = rec.height_mm / 25.4
            ft = int(total_in // 12)
            rec.height_ft = ft
            rec.height_in = total_in - ft * 12

    def _inverse_height_ftin(self):
        for rec in self:
            rec.height_mm = rec.height_ft * 304.8 + rec.height_in * 25.4

    @api.depends('height_mm')
    def _compute_height_inch_total(self):
        for rec in self:
            rec.height_inch_total = rec.height_mm / 25.4

    def _inverse_height_inch_total(self):
        for rec in self:
            rec.height_mm = rec.height_inch_total * 25.4

    @api.depends('width_mm', 'height_mm', 'length_uom')
    def _compute_size_display(self):
        for rec in self:
            if rec.length_uom == 'mm':
                # One trailing unit reads better when both numbers carry
                # the same one; ft/in can't do that, each part needs its own.
                rec.size_display = '%s × %s mm' % (
                    rec._trim(rec.width_mm), rec._trim(rec.height_mm))
            else:
                rec.size_display = '%s × %s' % (
                    rec._format_length(rec.width_mm),
                    rec._format_length(rec.height_mm),
                )

    @staticmethod
    def _trim(value):
        # 6.0 -> "6", 6.5 -> "6.5" — no trailing ".0" in a quote line
        return ('%.2f' % value).rstrip('0').rstrip('.') or '0'

    def _format_length(self, mm):
        """One length, rendered in whatever unit the Fenestration setting
        is currently on. Used for the sale line description and the Sale
        Order's Fenestration tab, so both always speak the same unit the
        design form is being edited in."""
        if self.length_uom == 'mm':
            return '%s mm' % self._trim(mm)
        total_in = mm / 25.4
        if self.length_uom == 'in':
            return '%s in' % self._trim(total_in)
        ft = int(total_in // 12)
        return '%s ft %s in' % (ft, self._trim(total_in - ft * 12))

    @api.depends('width_mm', 'height_mm')
    def _compute_area(self):
        for rec in self:
            m2 = (rec.width_mm / 1000.0) * (rec.height_mm / 1000.0)
            rec.area_sqm = m2
            rec.area_sqft = m2 * 10.7639

    # -- sale.order.line sync ----------------------------------------------
    # Done in create()/write(), NOT onchange: a design is edited on its own
    # form, not embedded in the Sale Order form, so there's no in-memory
    # parent record for an onchange to write back into. Confirmed this is
    # how core handles the same shape -- repair.repair.write() calls
    # _update_sale_order_line_price() to push onto its own sale_line_id
    # after super(), rather than relying on any onchange.
    SALE_LINE_SYNC_FIELDS = (
        'name', 'location', 'window_series_id', 'width_mm', 'height_mm',
        'qty', 'manual_rate', 'sale_order_line_id',
    )

    def _prepare_sale_line_description(self):
        self.ensure_one()
        parts = [self.name or '', self.location or '', self.size_display or '']
        if self.window_series_id:
            parts.append(self.window_series_id.display_name)
        return ' — '.join(p for p in parts if p)

    def _sync_sale_order_line(self):
        for rec in self:
            line = rec.sale_order_line_id
            if not line:
                continue
            vals = {
                'name': rec._prepare_sale_line_description(),
                'product_uom_qty': rec.qty,
            }
            # Only touch price_unit when there's an explicit manual rate --
            # otherwise leave whatever Odoo's own pricelist logic put there
            # alone. Real cost-cascade pricing is Step 3, not this one.
            if rec.manual_rate:
                vals['price_unit'] = rec.manual_rate * rec.area_sqft
            line.write(vals)

    @api.model_create_multi
    def create(self, vals_list):
        designs = super().create(vals_list)
        designs._sync_sale_order_line()
        return designs

    def write(self, vals):
        res = super().write(vals)
        if any(f in vals for f in self.SALE_LINE_SYNC_FIELDS):
            self._sync_sale_order_line()
        return res

    def unlink(self):
        # Deleting a design removes the quote line it priced onto. The
        # reverse already works without any code: sale_order_line_id is
        # ondelete='cascade', so deleting the line drops the design at the
        # DB level. Lines are collected before super() so the cascade has
        # nothing left to chase by the time they're unlinked.
        lines = self.sale_order_line_id
        res = super().unlink()
        lines.unlink()
        return res

    def action_open_design(self):
        self.ensure_one()
        return {
            'type': 'ir.actions.act_window',
            'res_model': 'aw.design',
            'res_id': self.id,
            'view_mode': 'form',
            'target': 'current',
        }

    def _incomplete_dimension_designs(self):
        """Designs still sitting at a zero width or height. Dimensions
        are allowed to be unset while a position is being configured --
        this is what the two points that genuinely need real numbers
        (exploding a BOM, confirming the order) check instead of a
        required= flag that would block creation itself."""
        return self.filtered(lambda d: not d.width_mm or not d.height_mm)

    def _check_dimensions_set(self):
        incomplete = self._incomplete_dimension_designs()
        if incomplete:
            raise UserError(_(
                "These positions still need a width and a height:\n%s",
                '\n'.join('- %s' % d.display_name for d in incomplete)))

    def action_explode(self):
        """Placeholder for the explosion engine — the Python port of the
        prototype's explode() function, reading real aw.profile.section.line
        and aw.hardware.set.line records (with their override/drop
        mechanism) instead of the JS SERIES.roles/HW objects. Deliberately
        not implemented in this pass; this module is the data model only.
        Raises NotImplementedError rather than silently doing nothing, so
        it's obvious in testing that this step hasn't landed yet."""
        # In place ahead of the engine itself: a cut list can't be
        # generated from a zero-sized opening, so this is one of the two
        # points where dimensions stop being optional.
        self._check_dimensions_set()
        raise NotImplementedError(
            "Explosion engine not yet ported — this method will read "
            "self.window_series_id's Profile Section / Hardware Set lines "
            "and generate aw.design.bom.line records the same way the JS "
            "prototype's explode() built QUOTE.designs[].prof/hw arrays.")
