# -*- coding: utf-8 -*-
from odoo import api, fields, models


class AwDesign(models.Model):
    """One configured window/door position — the direct port of the JS
    prototype's QUOTE.designs[] entry. The one deliberate departure from
    the prototype: this ties to a real sale.order.line instead of living
    in a standalone quote object, so Odoo's own pricing/discount/tax/PDF/
    portal machinery applies rather than being rebuilt in parallel.

    Row/leaf geometry lives in aw.design.row / aw.design.leaf (children).
    Profile cut list lives in aw.design.bom.line, GENERATED by the
    explosion engine — not part of this module yet, see action_explode().
    """
    _name = 'aw.design'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _description = 'Fenestration Design'
    _order = 'id'

    name = fields.Char(
        required=True, tracking=True,
        help="Position reference, e.g. 'D1' — matches the prototype's "
             "design.ref, shown on the cumulative cut-list table.")
    location = fields.Char(tracking=True, help="e.g. 'Drawing room', "
        "'Bathroom' — matches the prototype's design.loc.")
    company_id = fields.Many2one('res.company', default=lambda self: self.env.company)
    length_uom = fields.Selection(related='company_id.aw_length_uom', string='Length Unit')

    # -- geometry, overall opening --------------------------------------
    # mm is the stored source of truth (required); ft/in and inch_total
    # are compute+inverse display/entry pairs that read from and write
    # back to it, so editing in ANY unit keeps all three in sync and the
    # view can show only the pair matching company_id.aw_length_uom.
    width_mm = fields.Float(string='Width (mm)', required=True, tracking=True)
    width_ft = fields.Integer(string='Width (ft)',
        compute='_compute_width_ftin', inverse='_inverse_width_ftin')
    width_in = fields.Float(string='Width (in)',
        compute='_compute_width_ftin', inverse='_inverse_width_ftin',
        help="Decimals allowed, e.g. 6.5.")
    width_inch_total = fields.Float(string='Width (in)',
        compute='_compute_width_inch_total', inverse='_inverse_width_inch_total')

    height_mm = fields.Float(string='Height (mm)', required=True, tracking=True)
    height_ft = fields.Integer(string='Height (ft)',
        compute='_compute_height_ftin', inverse='_inverse_height_ftin')
    height_in = fields.Float(string='Height (in)',
        compute='_compute_height_ftin', inverse='_inverse_height_ftin',
        help="Decimals allowed, e.g. 6.5.")
    height_inch_total = fields.Float(string='Height (in)',
        compute='_compute_height_inch_total', inverse='_inverse_height_inch_total')

    # -- master-data links -----------------------------------------------
    # Confirmed against models/window_template.py: window_type_id is still
    # the exact field name on aw.window.template (and aw.profile.section/
    # aw.hardware.set), unchanged across the Kind/Type/Series restructure —
    # only its comodel moved to aw.window.series. Domain below is correct.
    window_series_id = fields.Many2one(
        'aw.window.series', required=True, tracking=True, ondelete='restrict')
    template_id = fields.Many2one(
        'aw.window.template', tracking=True, ondelete='set null',
        domain="[('window_type_id', '=', window_series_id)]",
        help="Optional starting default — populates Profile Section / "
             "Hardware Set / Glass Spec choices below when picked. Not "
             "required: a design can be built without one.")
    glass_spec_id = fields.Many2one(
        'aw.glass.spec', tracking=True, ondelete='restrict')

    # -- finish / thickness -----------------------------------------------
    # These are product.attribute.value records (the Finish/Thickness
    # attributes created for the profile product import), not a hardcoded
    # Selection — so this module never has its own copy of "what finishes
    # exist" to keep in sync with the product catalogue. Confirmed the
    # attribute names against the live import: "Finish" (xmlid
    # aw_attribute_finish) and "Thickness" (xmlid aw_attribute_thickness)
    # in aw_fenestration_core/data/chawla_attributes_data.xml. Domains by
    # xmlid rather than by name string, matching the pattern already used
    # for categ_id in aw_fenestration_core's profile_section.py/
    # hardware_set.py/glass_spec.py -- a renamed attribute wouldn't
    # silently break this the way name-matching would.
    finish_id = fields.Many2one(
        'product.attribute.value', tracking=True,
        domain=lambda self: [(
            'attribute_id', '=',
            self.env.ref('aw_fenestration_core.aw_attribute_finish').id,
        )])
    thickness_id = fields.Many2one(
        'product.attribute.value', tracking=True,
        domain=lambda self: [(
            'attribute_id', '=',
            self.env.ref('aw_fenestration_core.aw_attribute_thickness').id,
        )])

    # -- pricing override, matches prototype's d.manual -------------------
    manual_rate = fields.Float(
        string='Manual Rate (per sqft)',
        help="If set, overrides the calculated rate — matches the "
             "prototype's manual-override mechanism. Leave blank to use "
             "calculated pricing once the cost cascade exists.")

    # -- Sale integration ---------------------------------------------------
    sale_order_line_id = fields.Many2one(
        'sale.order.line', ondelete='cascade', index=True,
        help="The line this design prices onto. May be blank while a "
             "design is still being configured pre-quote.")
    sale_order_id = fields.Many2one(
        related='sale_order_line_id.order_id', store=True, readonly=True)

    # -- children -----------------------------------------------------------
    row_ids = fields.One2many('aw.design.row', 'design_id', string='Rows')
    bom_line_ids = fields.One2many(
        'aw.design.bom.line', 'design_id', string='Bill of Materials')

    row_count = fields.Integer(compute='_compute_counts')
    leaf_count = fields.Integer(compute='_compute_counts')
    area_sqm = fields.Float(compute='_compute_area', store=True, string='Area (m²)')
    area_sqft = fields.Float(compute='_compute_area', store=True, string='Area (sqft)')

    @api.depends('row_ids.leaf_ids')
    def _compute_counts(self):
        for rec in self:
            rec.row_count = len(rec.row_ids)
            rec.leaf_count = sum(len(r.leaf_ids) for r in rec.row_ids)

    @api.depends('width_mm')
    def _compute_width_ftin(self):
        for rec in self:
            total_in = rec.width_mm / 25.4
            ft = int(total_in // 12)
            rec.width_ft = ft
            rec.width_in = total_in - ft * 12

    def _inverse_width_ftin(self):
        for rec in self:
            rec.width_mm = rec.width_ft * 304.8 + rec.width_in * 25.4

    @api.depends('width_mm')
    def _compute_width_inch_total(self):
        for rec in self:
            rec.width_inch_total = rec.width_mm / 25.4

    def _inverse_width_inch_total(self):
        for rec in self:
            rec.width_mm = rec.width_inch_total * 25.4

    @api.depends('height_mm')
    def _compute_height_ftin(self):
        for rec in self:
            total_in = rec.height_mm / 25.4
            ft = int(total_in // 12)
            rec.height_ft = ft
            rec.height_in = total_in - ft * 12

    def _inverse_height_ftin(self):
        for rec in self:
            rec.height_mm = rec.height_ft * 304.8 + rec.height_in * 25.4

    @api.depends('height_mm')
    def _compute_height_inch_total(self):
        for rec in self:
            rec.height_inch_total = rec.height_mm / 25.4

    def _inverse_height_inch_total(self):
        for rec in self:
            rec.height_mm = rec.height_inch_total * 25.4

    @api.depends('width_mm', 'height_mm')
    def _compute_area(self):
        for rec in self:
            m2 = (rec.width_mm / 1000.0) * (rec.height_mm / 1000.0)
            rec.area_sqm = m2
            rec.area_sqft = m2 * 10.7639

    def action_explode(self):
        """Placeholder for the explosion engine — the Python port of the
        prototype's explode() function, reading real aw.profile.section.line
        and aw.hardware.set.line records (with their override/drop
        mechanism) instead of the JS SERIES.roles/HW objects. Deliberately
        not implemented in this pass; this module is the data model only.
        Raises NotImplementedError rather than silently doing nothing, so
        it's obvious in testing that this step hasn't landed yet."""
        raise NotImplementedError(
            "Explosion engine not yet ported — this method will read "
            "self.window_series_id's Profile Section / Hardware Set lines "
            "and generate aw.design.bom.line records the same way the JS "
            "prototype's explode() built QUOTE.designs[].prof/hw arrays.")
