# -*- coding: utf-8 -*-
from odoo import fields, models

ROLE_SELECTION = [
    ('frame', 'Frame'),
    ('sash', 'Sash'),
    ('interlock', 'Interlock'),
    ('bead', 'Glazing Bead'),
    ('mesh', 'Mesh'),
]


class AwDesignBomLine(models.Model):
    """One cut piece — the direct port of what the prototype's explode()
    pushed into its prof[] array, each carrying a {ref, loc, row, leaf,
    where} tag for the cumulative cut-list traceability (point #1 from
    the original planning: one growing table across every window in an
    order, each piece traceable back to which window/row/leaf it belongs
    to). GENERATED by action_explode() on aw.design — never hand-entered,
    same as the prototype's BOM was always computed, never typed in.

    Nesting into stock bars (14/16/18 ft), yield %, wastage reconciliation
    and the cumulative multi-design cut table are NOT part of this model —
    those operate across every aw.design on an order at once (same as the
    prototype's cutPlan() pooled pieces across every QUOTE.designs[]
    entry), so they belong on a report/wizard keyed off sale.order, not
    stored per-line here.
    """
    _name = 'aw.design.bom.line'
    _description = 'Fenestration Design BOM Line'
    _order = 'design_id, sequence, id'

    design_id = fields.Many2one('aw.design', required=True, ondelete='cascade', index=True)
    sequence = fields.Integer(default=10)

    role = fields.Selection(ROLE_SELECTION, required=True)
    product_id = fields.Many2one('product.product', required=True, ondelete='restrict')

    length_mm = fields.Float(required=True)
    qty = fields.Integer(required=True, default=1,
        help="Pieces of this exact length needed — e.g. 2 for a pair of "
             "top/bottom rails. Multiply by aw.design.qty for the total "
             "physical count across all units of this design.")

    # traceability tag — matches the prototype's tag:{ref,loc,row,leaf,where}
    row_index = fields.Integer(string='Row #')
    leaf_index = fields.Integer(string='Leaf #')
    where = fields.Char(help="Human-readable location, e.g. 'sash top/bottom', "
        "'vertical mullion' — matches the prototype's tag.where used on "
        "the Report tab's cut list.")

    unit_cost = fields.Float(
        help="Rate at time of explosion (PKR/ft or equivalent) — snapshot, "
             "not a live lookup, same reasoning as the earlier decision "
             "that a quote must not silently recost when reopened.")
