# -*- coding: utf-8 -*-
from odoo import api, fields, models

ROLE_SELECTION = [
    ('frame', 'Frame'),
    ('sash', 'Sash'),
    ('interlock', 'Interlock'),
    ('bead', 'Glazing Bead'),
    ('mesh', 'Mesh'),
]


class AwDesignBomLine(models.Model):
    """One cut piece — the direct port of what the prototype's explode()
    pushed into its prof[] array, each carrying a {ref, loc, row, leaf,
    where} tag for the cumulative cut-list traceability (point #1 from
    the original planning: one growing table across every window in an
    order, each piece traceable back to which window/row/leaf it belongs
    to). GENERATED by action_explode() on aw.design — never hand-entered,
    same as the prototype's BOM was always computed, never typed in.

    Nesting into stock bars (14/16/18 ft), yield %, wastage reconciliation
    and the cumulative multi-design cut table are NOT part of this model —
    those operate across every aw.design on an order at once (same as the
    prototype's cutPlan() pooled pieces across every QUOTE.designs[]
    entry), so they belong on a report/wizard keyed off sale.order, not
    stored per-line here.
    """
    _name = 'aw.design.bom.line'
    _description = 'Fenestration Design BOM Line'
    _order = 'design_id, sequence, id'

    design_id = fields.Many2one('aw.design', required=True, ondelete='cascade', index=True)
    sequence = fields.Integer(default=10)

    # kind replaces role as what the engine writes. role is kept and no
    # longer required: it was the dormant frame/sash/interlock/bead/mesh
    # Selection from before positions existed, and dropping it would lose
    # whatever an old row said.
    kind = fields.Selection([
        ('profile', 'Profile'),
        ('glass', 'Glass'),
        ('hardware', 'Hardware'),
        ('mesh', 'Mesh'),
        ('infill', 'Infill'),
        ('grid', 'Grid'),
    ], required=True, default='profile', index=True)
    role = fields.Selection(ROLE_SELECTION)
    # Not required: the engine still reports a line whose product is
    # missing, because a silent gap in a cut list is worse than a line
    # that says what is wrong. The checks flag it.
    product_id = fields.Many2one('product.product', ondelete='restrict')

    length_mm = fields.Float()
    cut_angle = fields.Selection([
        ('45', '45 deg'), ('90', '90 deg'),
    ], default='90')
    label = fields.Char(help="Where this piece goes, e.g. 'P2 Palay - Top'.")
    # Stable identity for one physical piece (spec 6c-B). Assigned by
    # the explosion from the design's own geometry, so it survives
    # re-optimising the cutting plan -- which is the whole point: the
    # shop writes it on the bar.
    piece_ref = fields.Char(string='Ref', index=True)
    unit_no = fields.Integer(
        string='Unit', default=1,
        help="Which of the position's units this piece belongs to.")
    panel_no = fields.Integer(string='Panel')
    glass_spec_id = fields.Many2one('aw.glass.spec', ondelete='restrict')
    glass_w = fields.Float(string='Width (mm)')
    glass_h = fields.Float(string='Height (mm)')
    area_sqm = fields.Float(compute='_compute_area_sqm', store=True)
    qty = fields.Integer(required=True, default=1,
        help="Pieces of this exact length needed — e.g. 2 for a pair of "
             "top/bottom rails. Multiply by aw.design.qty for the total "
             "physical count across all units of this design.")

    # traceability tag — matches the prototype's tag:{ref,loc,row,leaf,where}
    row_index = fields.Integer(string='Row #')
    leaf_index = fields.Integer(string='Leaf #')
    where = fields.Char(help="Human-readable location, e.g. 'sash top/bottom', "
        "'vertical mullion' — matches the prototype's tag.where used on "
        "the Report tab's cut list.")

    unit_cost = fields.Float(
        help="Rate at time of explosion (PKR/ft or equivalent) — snapshot, "
             "not a live lookup, same reasoning as the earlier decision "
             "that a quote must not silently recost when reopened.")

    @api.depends('glass_w', 'glass_h', 'qty')
    def _compute_area_sqm(self):
        for line in self:
            line.area_sqm = (
                (line.glass_w or 0.0) * (line.glass_h or 0.0)
                / 1000000.0 * (line.qty or 0))
